// Code generated by protoc-gen-go.
// source: PopcodesStore.proto
// DO NOT EDIT!

/*
Package PopcodesStore is a generated protocol buffer package.

It is generated from these files:
	PopcodesStore.proto

It has these top-level messages:
	Popcodes
	OTX
*/
package PopcodesStore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Popcodes struct {
	PublicKey []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Counter   []byte `protobuf:"bytes,2,opt,name=Counter,proto3" json:"Counter,omitempty"`
	Ouputs    []*OTX `protobuf:"bytes,3,rep,name=Ouputs" json:"Ouputs,omitempty"`
}

func (m *Popcodes) Reset()         { *m = Popcodes{} }
func (m *Popcodes) String() string { return proto.CompactTextString(m) }
func (*Popcodes) ProtoMessage()    {}

func (m *Popcodes) GetOuputs() []*OTX {
	if m != nil {
		return m.Ouputs
	}
	return nil
}

type OTX struct {
	Owners    []byte `protobuf:"bytes,1,opt,name=Owners,proto3" json:"Owners,omitempty"`
	Idx       int32  `protobuf:"varint,2,opt,name=Idx" json:"Idx,omitempty"`
	Threshold int32  `protobuf:"varint,3,opt,name=Threshold" json:"Threshold,omitempty"`
	Amount    int32  `protobuf:"varint,4,opt,name=Amount" json:"Amount,omitempty"`
	Data      string `protobuf:"bytes,5,opt,name=Data" json:"Data,omitempty"`
	Creator   []byte `protobuf:"bytes,6,opt,name=Creator,proto3" json:"Creator,omitempty"`
}

func (m *OTX) Reset()         { *m = OTX{} }
func (m *OTX) String() string { return proto.CompactTextString(m) }
func (*OTX) ProtoMessage()    {}
