// Code generated by protoc-gen-go.
// source: popcodesTX.proto
// DO NOT EDIT!

/*
Package popcodesTX is a generated protocol buffer package.

It is generated from these files:
	popcodesTX.proto

It has these top-level messages:
	CreateTX
	TransferOwners
	Unitize
	Combine
	CombineSources
*/
package popcodesTX

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateTX struct {
	Address       []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Amount        int32  `protobuf:"varint,2,opt,name=Amount" json:"Amount,omitempty"`
	Data          string `protobuf:"bytes,3,opt,name=Data" json:"Data,omitempty"`
	CreatorPubKey []byte `protobuf:"bytes,4,opt,name=CreatorPubKey,proto3" json:"CreatorPubKey,omitempty"`
	CreatorSig    []byte `protobuf:"bytes,5,opt,name=CreatorSig,proto3" json:"CreatorSig,omitempty"`
}

func (m *CreateTX) Reset()         { *m = CreateTX{} }
func (m *CreateTX) String() string { return proto.CompactTextString(m) }
func (*CreateTX) ProtoMessage()    {}

type TransferOwners struct {
	Address       []byte   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Output        int32    `protobuf:"varint,2,opt,name=Output" json:"Output,omitempty"`
	Owners        [][]byte `protobuf:"bytes,3,rep,name=Owners,proto3" json:"Owners,omitempty"`
	PrevOwnerSigs [][]byte `protobuf:"bytes,4,rep,name=PrevOwnerSigs,proto3" json:"PrevOwnerSigs,omitempty"`
	PopcodeSig    []byte   `protobuf:"bytes,5,opt,name=PopcodeSig,proto3" json:"PopcodeSig,omitempty"`
}

func (m *TransferOwners) Reset()         { *m = TransferOwners{} }
func (m *TransferOwners) String() string { return proto.CompactTextString(m) }
func (*TransferOwners) ProtoMessage()    {}

type Unitize struct {
	SourceAddress []byte   `protobuf:"bytes,1,opt,name=SourceAddress,proto3" json:"SourceAddress,omitempty"`
	SourceOutput  int32    `protobuf:"varint,2,opt,name=SourceOutput" json:"SourceOutput,omitempty"`
	DestAddress   [][]byte `protobuf:"bytes,3,rep,name=DestAddress,proto3" json:"DestAddress,omitempty"`
	DestAmounts   [][]byte `protobuf:"bytes,4,rep,name=DestAmounts,proto3" json:"DestAmounts,omitempty"`
	OwnerSigs     [][]byte `protobuf:"bytes,5,rep,name=OwnerSigs,proto3" json:"OwnerSigs,omitempty"`
}

func (m *Unitize) Reset()         { *m = Unitize{} }
func (m *Unitize) String() string { return proto.CompactTextString(m) }
func (*Unitize) ProtoMessage()    {}

type Combine struct {
	Address       []byte            `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Sources       []*CombineSources `protobuf:"bytes,2,rep,name=sources" json:"sources,omitempty"`
	CreatorPubKey []byte            `protobuf:"bytes,3,opt,name=CreatorPubKey,proto3" json:"CreatorPubKey,omitempty"`
	CreatorSig    []byte            `protobuf:"bytes,4,opt,name=CreatorSig,proto3" json:"CreatorSig,omitempty"`
	OwnerSigs     [][]byte          `protobuf:"bytes,5,rep,name=OwnerSigs,proto3" json:"OwnerSigs,omitempty"`
	PopcodeSigs   []byte            `protobuf:"bytes,6,opt,name=PopcodeSigs,proto3" json:"PopcodeSigs,omitempty"`
}

func (m *Combine) Reset()         { *m = Combine{} }
func (m *Combine) String() string { return proto.CompactTextString(m) }
func (*Combine) ProtoMessage()    {}

func (m *Combine) GetSources() []*CombineSources {
	if m != nil {
		return m.Sources
	}
	return nil
}

type CombineSources struct {
	SourceOutput int32 `protobuf:"varint,1,opt,name=SourceOutput" json:"SourceOutput,omitempty"`
	SourceAmount int32 `protobuf:"varint,2,opt,name=SourceAmount" json:"SourceAmount,omitempty"`
}

func (m *CombineSources) Reset()         { *m = CombineSources{} }
func (m *CombineSources) String() string { return proto.CompactTextString(m) }
func (*CombineSources) ProtoMessage()    {}
