// Code generated by protoc-gen-go.
// source: txcache.proto
// DO NOT EDIT!

/*
Package txcache is a generated protocol buffer package.

It is generated from these files:
	txcache.proto

It has these top-level messages:
	TXCache
*/
package txcache

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TXCache struct {
	Cache map[string]bool `protobuf:"bytes,1,rep,name=cache" json:"cache,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *TXCache) Reset()         { *m = TXCache{} }
func (m *TXCache) String() string { return proto.CompactTextString(m) }
func (*TXCache) ProtoMessage()    {}

func (m *TXCache) GetCache() map[string]bool {
	if m != nil {
		return m.Cache
	}
	return nil
}
